---
- name: Create VPC Network
  gcp_compute_network:
    name: gcp-ansible-network
    auto_create_subnetworks: yes
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: network

- name: Create subnet within above VPC network
  gcp_compute_subnetwork:
    name: gcp-ansible-subnet
    region: "{{ gcp_region }}"
    network: "{{ network }}"
    ip_cidr_range: "{{ ip_cidr_range }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: subnet

- name: Create firewall rule to allow port 80 and 22 for all source IPs
  gcp_compute_firewall:
    name: ansible-firewall
    network: "{{ network }}"
    allowed:
    - ip_protocol: tcp
      ports: ['80','22']
    target_tags:
      - gcp-ansible
    source_ranges: ['0.0.0.0/0']
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: firewall

- name: Create IP address for instance name
  gcp_compute_address:
    name: "{{ instance_name }}"
    region: "{{ gcp_region }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: address

- name: Create disk for new instance
  gcp_compute_disk:
    name: "{{ instance_name }}"
    size_gb: "{{ disk_size_gb }}"
    source_image: 'projects/centos-cloud/global/images/centos-7-v20190116'
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: disk

- name: Create new instance
  gcp_compute_instance:
    state: present
    name: "{{ instance_name }}"
    machine_type: "{{ machine_type }}"
    disks:
    - auto_delete: true
      boot: true
      source: "{{ disk }}"
    network_interfaces:
    - network: "{{ network }}"
      subnetwork: "{{ subnet }}"
      access_configs:
      - name: External NAT
        nat_ip: "{{ address }}"
        type: ONE_TO_ONE_NAT
    zone: "{{ gcp_zone }}"
    tags:
      items:
        - gcp-ansible
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
  register: instance

- debug:
    var: instance
